theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
cursorline = true
bufferline = "always"
true-color = true
rulers = [120]
# Minimum severity to show a diagnostic after the end of a line
end-of-line-diagnostics = "hint"
# Scrolling Behavior
scroll-lines = 3
scrolloff = 5

# Turn on LSP-powered completion
auto-completion = true           # shows popup as you type
completion-timeout = 100         # how quickly after typing to show it
preview-completion-insert = true # preview selection inline
completion-trigger-len = 1       # how many chars before popup triggers

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

# other existing settings
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 60000 # 1 minute delay if inactivity before auto save

[editor.inline-diagnostics]
cursor-line = "error" # Show inline diagnostics when the cursor is on the line
other-lines = "disable" # Don't expand diagnostics unless the cursor is on the line


[editor.indent-guides]
character = "╎"
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.insert]
C-h = "move_char_left"
C-l = "move_char_right"
C-j = "move_line_down"
C-k = "move_line_up"

[keys.normal]
"ret" = "goto_word"
C-j   = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k   = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
D     = ["extend_to_line_end", "delete_selection"]

# Yazi
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':set mouse false', # Force Helix to drop mouse tracking
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse true', # Force Helix to re-enable Kitty's mouse protocol
]

# Lazygit binding
C-g = [
  ":set mouse false",
  ":new", 
  ":insert-output lazygit", 
  ":buffer-close!", 
  ":redraw",
  ":set mouse true"
]

# Next word selection hack
G = [
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "select_all",
  "select_regex"
]

# shortcut to format then save
W = [":format", ":w"]
C-space = "signature_help"

[editor.file-picker]
hidden = false
# requires a .ignore file in the root, good for ignoring vendor/
ignore = true
git-ignore = true
git-global = true

[keys.normal.space]
# B Displays git blame
B = ":echo %sh{hash=$(git blame -L \"%{cursor_line}\",+1 \"%{buffer_name}\" 2>/dev/null | awk '{print $1}'); if [ -z \"$hash\" ]; then echo \"(Untracked file)\"; elif echo \"$hash\" | grep -q '^0\\+$'; then echo \"(Uncommitted changes)\"; else git show -s --format='%%h %%an [%%ad]: %%s' --date=format-local:'%%Y-%%m-%%d %%I:%%M %%p' \"$hash\" | sed 's/%%/%%%%/g'; fi}"
# Space + q closes the buffer
q = ":buffer-close!"
# Space + Q force quits Helix entirely
Q = ":quit!"

[keys.normal.space.t]
c = ":pipe ccase --to camel"
t = ":pipe ccase --to title"
p = ":pipe ccase --to pascal"
s = ":pipe ccase --to snake"
u = ":pipe ccase --to upper"
l = ":pipe ccase --to lower"
